disallowed-methods = [
    { path = "cargo_metadata::camino::Utf8Path::canonicalize_utf8", reason = "use `canonicalize_utf8` instead" },
    { path = "camino::Utf8Path::canonicalize_utf8", reason = "use `canonicalize_utf8` instead" },
]
