[package]
name = "fake_package"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
cargo_utils.workspace = true
cargo_metadata.workspace = true
serde_json.workspace = true
